#### POD config (run one time)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-x11-novnc-docker
  labels:
    application: wine-x11-novnc-docker
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
        application: wine-x11-novnc-docker
  template:
    metadata:
      labels:
        application: wine-x11-novnc-docker
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: wine-x11-novnc-docker
        image: solarkennedy/wine-x11-novnc-docker
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          #- '--tail-log'
        ### checks that vnc server is up and running
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: wine-x11-novnc-docker
  name: wine-x11-novnc-docker
spec:
  externalName: wine-x11-novnc-docker
  ports:
  - name: rdp-port-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    application: wine-x11-novnc-docker
  type: NodePort
# Use type loadbalancer if needed
#  type: LoadBalancer

